version: "3.8"
services:
  api:
    build: .
    ports:
      - "4000:4000"
    environment:
      ? CLIENT_HOSTS
      ? JWT_SECRET
      ? NODE_ENV
      PRISMA_ENDPOINT: http://prisma:4466
      ? PRISMA_SERVICE
      ? PRISMA_STAGE
      ? PRISMA_SERVICE_SECRET
    command: npm run dev
    volumes:
      - .:/usr/app

  prisma:
    image: prismagraphql/prisma:1.28
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
            rawAccess: true

  postgres:
    image: postgres:10.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data

  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "dinismiguelcosta@hotmail.com"
      PGADMIN_DEFAULT_PASSWORD: "rootpass"
    ports:
      - "16543:80"
    depends_on:
      - api

volumes:
  ? postgres
